/**
 * Gomematic OpenAPI
 * API definition for Gomematic
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient'
import AuthLogin from './model/AuthLogin'
import AuthToken from './model/AuthToken'
import AuthVerify from './model/AuthVerify'
import GeneralError from './model/GeneralError'
import Profile from './model/Profile'
import Team from './model/Team'
import TeamUser from './model/TeamUser'
import TeamUserParams from './model/TeamUserParams'
import User from './model/User'
import UserTeamParams from './model/UserTeamParams'
import ValidationError from './model/ValidationError'
import ValidationErrorErrors from './model/ValidationErrorErrors'
import AuthApi from './api/AuthApi'
import ProfileApi from './api/ProfileApi'
import TeamApi from './api/TeamApi'
import UserApi from './api/UserApi'

/**
* API_definition_for_Gomematic.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Gomematic = require('gomematic/index'); // See note below*.
* var xxxSvc = new Gomematic.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Gomematic.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['gomematic/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Gomematic.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Gomematic.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module gomematic/index
* @version 1.0.0-alpha1
*/
export {
  /**
     * The ApiClient constructor.
     * @property {module:gomematic/ApiClient}
     */
  ApiClient,

  /**
     * The AuthLogin model constructor.
     * @property {module:gomematic/model/AuthLogin}
     */
  AuthLogin,

  /**
     * The AuthToken model constructor.
     * @property {module:gomematic/model/AuthToken}
     */
  AuthToken,

  /**
     * The AuthVerify model constructor.
     * @property {module:gomematic/model/AuthVerify}
     */
  AuthVerify,

  /**
     * The GeneralError model constructor.
     * @property {module:gomematic/model/GeneralError}
     */
  GeneralError,

  /**
     * The Profile model constructor.
     * @property {module:gomematic/model/Profile}
     */
  Profile,

  /**
     * The Team model constructor.
     * @property {module:gomematic/model/Team}
     */
  Team,

  /**
     * The TeamUser model constructor.
     * @property {module:gomematic/model/TeamUser}
     */
  TeamUser,

  /**
     * The TeamUserParams model constructor.
     * @property {module:gomematic/model/TeamUserParams}
     */
  TeamUserParams,

  /**
     * The User model constructor.
     * @property {module:gomematic/model/User}
     */
  User,

  /**
     * The UserTeamParams model constructor.
     * @property {module:gomematic/model/UserTeamParams}
     */
  UserTeamParams,

  /**
     * The ValidationError model constructor.
     * @property {module:gomematic/model/ValidationError}
     */
  ValidationError,

  /**
     * The ValidationErrorErrors model constructor.
     * @property {module:gomematic/model/ValidationErrorErrors}
     */
  ValidationErrorErrors,

  /**
    * The AuthApi service constructor.
    * @property {module:gomematic/api/AuthApi}
    */
  AuthApi,

  /**
    * The ProfileApi service constructor.
    * @property {module:gomematic/api/ProfileApi}
    */
  ProfileApi,

  /**
    * The TeamApi service constructor.
    * @property {module:gomematic/api/TeamApi}
    */
  TeamApi,

  /**
    * The UserApi service constructor.
    * @property {module:gomematic/api/UserApi}
    */
  UserApi
}
